SELECT DISTINCT PRICES.PRODUCT_ID, IFNULL(ROUND(SUM(PRICE*UNITS)/SUM(UNITS),2),0) AS AVERAGE_PRICE
FROM PRICES
LEFT JOIN UNITSSOLD
ON PRICES.PRODUCT_ID = UNITSSOLD.PRODUCT_ID
AND UNITSSOLD.PURCHASE_DATE BETWEEN PRICES.START_DATE AND PRICES.END_DATE
GROUP BY PRODUCT_ID;