SELECT 
STUDENTS.STUDENT_ID,STUDENTS.STUDENT_NAME,SUBJECTS.SUBJECT_NAME,
COUNT(EXAMINATIONS.STUDENT_ID) AS ATTENDED_EXAMS FROM  STUDENTS
CROSS JOIN 
SUBJECTS
LEFT JOIN
EXAMINATIONS ON STUDENTS.STUDENT_ID = EXAMINATIONS.STUDENT_ID
AND SUBJECTS.SUBJECT_NAME=EXAMINATIONS.SUBJECT_NAME
GROUP BY STUDENTS.STUDENT_ID,SUBJECTS.SUBJECT_NAME,STUDENTS.STUDENT_NAME
ORDER BY STUDENTS.STUDENT_ID,SUBJECTS.SUBJECT_NAME;