-- SELECT DISTINCT SALES.PRODUCT_ID,
-- MIN(YEAR) AS FIRST_YEAR,
-- QUANTITY,
-- PRICE FROM SALES
-- JOIN PRODUCT ON 
-- SALES.PRODUCT_ID = PRODUCT.PRODUCT_ID
-- GROUP BY PRODUCT_ID;

SELECT  DISTINCT PRODUCT_ID,YEAR AS FIRST_YEAR, QUANTITY,PRICE
FROM SALES
WHERE (YEAR,PRODUCT_ID) IN (SELECT MIN(YEAR),PRODUCT_ID FROM SALES GROUP BY PRODUCT_ID);
