SELECT SUBSTRING(TRANS_DATE,1,7)AS MONTH,
COUNTRY,
COUNT(ID) AS TRANS_COUNT,
SUM(CASE WHEN STATE='APPROVED' THEN 1 ELSE 0 END) AS APPROVED_COUNT,
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(CASE WHEN STATE='APPROVED' THEN AMOUNT ELSE 0 END)
AS APPROVED_TOTAL_AMOUNT 
FROM TRANSACTIONS
GROUP BY  MONTH,COUNTRY;