# Write your MySQL query statement below
SELECT 
QUERY_NAME,
ROUND(SUM(RATING/POSITION)/COUNT(QUERY_NAME),2) AS QUALITY,
ROUND(SUM(RATING<3)*100/COUNT(QUERY_NAME),2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES
WHERE QUERY_NAME IS NOT NULL
GROUP BY QUERY_NAME;