# Write your MySQL query statement below

SELECT PRODUCT_NAME, SUM(UNIT) AS UNIT  FROM PRODUCTS
JOIN ORDERS
ON PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT_ID
WHERE ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY PRODUCTS.PRODUCT_ID 
HAVING UNIT >=100;