# Write your MySQL query statement below
SELECT SIGNUPS.USER_ID,
IFNULL(ROUND(SUM(CASE WHEN ACTION ='CONFIRMED' THEN 1 ELSE 0 END)/COUNT(CONFIRMATIONS.USER_ID),2),0) AS CONFIRMATION_RATE
FROM SIGNUPS
LEFT JOIN 
CONFIRMATIONS
ON SIGNUPS.USER_ID=CONFIRMATIONS.USER_ID
GROUP BY USER_ID;