SELECT PROJECT_ID,ROUND(SUM(EXPERIENCE_YEARS)/COUNT(EMPLOYEE.EMPLOYEE_ID),2) AS AVERAGE_YEARS
FROM PROJECT
JOIN EMPLOYEE
ON PROJECT.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
AND EXPERIENCE_YEARS IS NOT NULL
GROUP BY PROJECT_ID;